/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.JList;

/**
 *
 * @author Ali PF Njie
 */
public class Teams extends javax.swing.JFrame {

    /**
     * Creates new form Teams
     */
    public Teams() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        teamList = new javax.swing.JList();
        viewTeam = new javax.swing.JButton();
        updateTeam = new javax.swing.JButton();
        deleteTeam = new javax.swing.JButton();
        createTeam = new javax.swing.JButton();
        logout = new javax.swing.JButton();
        team = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        loadFromFile = new javax.swing.JButton();
        saveToFile = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu");
        setResizable(false);

        teamList.setFont(new java.awt.Font("Cambria", 0, 36)); // NOI18N
        teamList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(teamList);

        viewTeam.setFont(new java.awt.Font("Papyrus", 0, 18)); // NOI18N
        viewTeam.setText("View Selected Team");
        viewTeam.setToolTipText("Show the info of the team, including players and managers.");

        updateTeam.setFont(new java.awt.Font("Papyrus", 0, 18)); // NOI18N
        updateTeam.setText("Update Selected Team");
        updateTeam.setToolTipText("Updates the info of a selected team.");
        updateTeam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateTeamActionPerformed(evt);
            }
        });

        deleteTeam.setFont(new java.awt.Font("Papyrus", 0, 18)); // NOI18N
        deleteTeam.setText("Delete Selected Team");
        deleteTeam.setToolTipText("Deletes the selected team.");

        createTeam.setFont(new java.awt.Font("Papyrus", 0, 18)); // NOI18N
        createTeam.setText("Create New Team");
        createTeam.setToolTipText("Creates a new team");

        logout.setFont(new java.awt.Font("Papyrus", 0, 18)); // NOI18N
        logout.setText("<< Log out");

        team.setFont(new java.awt.Font("Gabriola", 1, 36)); // NOI18N
        team.setText("Welcome to APL Manager");

        jLabel4.setFont(new java.awt.Font("Gabriola", 0, 27)); // NOI18N
        jLabel4.setText("List of Current Teams in the APL");

        loadFromFile.setFont(new java.awt.Font("Papyrus", 0, 18)); // NOI18N
        loadFromFile.setText("Load Team From FIle");
        loadFromFile.setToolTipText("Loads a selected text file, in a particular format, as a team.");

        saveToFile.setFont(new java.awt.Font("Papyrus", 0, 18)); // NOI18N
        saveToFile.setText("Save Team To File");
        saveToFile.setToolTipText("Saves the selected team to a text file with the team name as the title");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 535, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(createTeam, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(viewTeam, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(updateTeam, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(deleteTeam, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(loadFromFile, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(saveToFile, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(253, 253, 253)
                        .addComponent(team)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(team, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(createTeam)
                        .addGap(18, 18, 18)
                        .addComponent(viewTeam)
                        .addGap(18, 18, 18)
                        .addComponent(updateTeam)
                        .addGap(18, 18, 18)
                        .addComponent(deleteTeam)
                        .addGap(18, 18, 18)
                        .addComponent(loadFromFile)
                        .addGap(18, 18, 18)
                        .addComponent(saveToFile)))
                .addGap(18, 18, 18)
                .addComponent(logout)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void updateTeamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateTeamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_updateTeamActionPerformed
    
    // Accessor methods for the buttons
    public JButton getCreateTeamBtn(){
        return createTeam;
    }
    
    public JButton getDeleteTeamBtn(){
        return deleteTeam;
    }
    
    public JButton getUpdateTeamBtn(){
        return updateTeam;
    }
    
    public JButton getViewTeamBtn(){
        return viewTeam;
    }
    
    public JButton getLogoutBtn(){
        return logout;
    }
    
    public JButton getLoadTeam(){
        return loadFromFile;
    }
    
    public JButton getSaveTeam(){
        return saveToFile;
    }
    public JList getTeamList(){
        return teamList;
    }
    
   /* public JFileChooser getFileChooser(){
        return fileChooser;
    }*/
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Teams.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Teams.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Teams.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Teams.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Teams().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton createTeam;
    private javax.swing.JButton deleteTeam;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton loadFromFile;
    private javax.swing.JButton logout;
    private javax.swing.JButton saveToFile;
    private javax.swing.JLabel team;
    private javax.swing.JList teamList;
    private javax.swing.JButton updateTeam;
    private javax.swing.JButton viewTeam;
    // End of variables declaration//GEN-END:variables
}
